name: "TestFlight PM - Enhanced Issue Management"
description: "Intelligent TestFlight feedback processing with LLM enhancement and automated issue creation"
author: "TestFlight PM Team"

inputs:
  # Core Configuration
  testflight_issuer_id:
    description: "App Store Connect API Issuer ID"
    required: true
  testflight_key_id:
    description: "App Store Connect API Key ID" 
    required: true
  testflight_private_key:
    description: "App Store Connect API Private Key (base64 encoded)"
    required: true
  app_id:
    description: "TestFlight App ID"
    required: true

  # Issue Management Platform Configuration
  platform:
    description: "Issue management platform (github or linear)"
    required: false
    default: "github"
  
  # GitHub Configuration
  github_token:
    description: "GitHub Personal Access Token"
    required: false
  github_owner:
    description: "GitHub repository owner"
    required: false
  github_repo:
    description: "GitHub repository name"
    required: false

  # Linear Configuration  
  linear_api_token:
    description: "Linear API Token"
    required: false
  linear_team_id:
    description: "Linear Team ID"
    required: false

  # LLM Enhancement Configuration
  enable_llm_enhancement:
    description: "Enable LLM-powered issue enhancement"
    required: false
    default: "false"
  
  llm_provider:
    description: "Primary LLM provider (openai, anthropic, google, deepseek, xai)"
    required: false
    default: "openai"
  
  llm_fallback_providers:
    description: "Comma-separated list of fallback providers"
    required: false
    default: "anthropic,google"

  # LLM API Keys
  openai_api_key:
    description: "OpenAI API Key for LLM enhancement"
    required: false
  anthropic_api_key:
    description: "Anthropic API Key for Claude models"
    required: false
  google_api_key:
    description: "Google API Key for Gemini models"
    required: false
  deepseek_api_key:
    description: "DeepSeek API Key for DeepSeek models"
    required: false
  xai_api_key:
    description: "xAI API Key for Grok models"
    required: false

  # LLM Model Configuration
  openai_model:
    description: "OpenAI model to use"
    required: false
    default: "gpt-4.1-mini"
  anthropic_model:
    description: "Anthropic model to use"
    required: false
    default: "claude-3.7-sonnet"
  google_model:
    description: "Google model to use" 
    required: false
    default: "gemini-2.0-flash"
  deepseek_model:
    description: "DeepSeek model to use"
    required: false
    default: "deepseek-v3"
  xai_model:
    description: "xAI model to use"
    required: false
    default: "grok-3"

  # LLM Cost Controls
  max_llm_cost_per_run:
    description: "Maximum LLM cost per action run (USD)"
    required: false
    default: "5.00"
  max_llm_cost_per_month:
    description: "Maximum LLM cost per month (USD)"
    required: false
    default: "200.00"
  max_tokens_per_issue:
    description: "Maximum tokens per issue enhancement"
    required: false
    default: "4000"

  # Processing Configuration
  enable_duplicate_detection:
    description: "Enable duplicate issue detection"
    required: false
    default: "true"
  duplicate_detection_days:
    description: "Number of days to look back for duplicates"
    required: false
    default: "7"
  
  enable_codebase_analysis:
    description: "Enable codebase analysis for enhanced issue correlation"
    required: false
    default: "true"
  
  codebase_analysis_depth:
    description: "Depth of codebase analysis (basic, moderate, deep)"
    required: false
    default: "moderate"

  # Processing Filters
  enable_crash_processing:
    description: "Process crash reports"
    required: false
    default: "true"
  enable_feedback_processing:
    description: "Process user feedback"
    required: false
    default: "true"
  
  min_feedback_length:
    description: "Minimum feedback text length to process"
    required: false
    default: "10"
  
  processing_window_hours:
    description: "Hours to look back for new feedback"
    required: false
    default: "24"

  # Issue Labeling
  crash_labels:
    description: "Comma-separated labels for crash issues"
    required: false
    default: "bug,crash,testflight"
  feedback_labels:
    description: "Comma-separated labels for feedback issues"
    required: false
    default: "enhancement,feedback,testflight"
  additional_labels:
    description: "Additional labels to apply to all issues"
    required: false
    default: ""

  # Advanced Configuration
  dry_run:
    description: "Run in dry-run mode (no issues created)"
    required: false
    default: "false"
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
  
  workspace_root:
    description: "Root directory for codebase analysis"
    required: false
    default: "."

outputs:
  issues_created:
    description: "Number of issues created"
  issues_updated:
    description: "Number of issues updated"
  crashes_processed:
    description: "Number of crash reports processed"
  feedback_processed:
    description: "Number of feedback items processed"
  llm_requests_made:
    description: "Number of LLM API requests made"
  llm_cost_incurred:
    description: "Total LLM cost incurred (USD)"
  processing_summary:
    description: "JSON summary of processing results"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "alert-circle"
  color: "blue" 